### ISSUE TITLE
Minecraft not recognizing mod version

### ISSUE THREAD

**Issue by JacksonMan9000** [team-abnormals/blueprint#137]
Whenever I try to use this mod in 1.16.5, when Minecraft loads it says that the mod is for 1.18.1 when it is not. I have tried multiple versions of the mod but every time it says this.

**Comment by bageldotjpg** [comment]
What is the name of the file you have installed

**Comment by JacksonMan9000** [comment]
abnormals_core-1.16.5-3.3.0

**Comment by JacksonMan9000** [comment]
But I have also tried the newest version and an older version.

**Comment by SmellyModder** [comment]
Show us a screenshot of your mods folder.

**Comment by JacksonMan9000** [comment]
Well, I pinpointed the problem. In the download area, they don't have blueprint mod for 1.16.5 but they do have the abnormals core in the blueprint mod download section. Does blueprint get included with abnormal core for 1.16.5?

**Comment by SmellyModder** [comment]
Abnormals Core was renamed to Blueprint.
