### ISSUE TITLE
Crash report: Mod Failed to Load

### ISSUE THREAD

**Issue by Atlantispy** [team-abnormals/blueprint#138]
[crash-2022-02-09_20.53.25-fml.txt](https://github.com/team-abnormals/blueprint/files/8036175/crash-2022-02-09_20.53.25-fml.txt)
[latest.log](https://github.com/team-abnormals/blueprint/files/8036176/latest.log)

Mentioned this on discord too but thought I'd report here.

Crash received when updating to 5.1.0 from 5.0. No Issues prior to that.

**Comment by SmellyModder** [comment]
Closed in https://github.com/team-abnormals/blueprint/commit/c6b021fb2296d1e83c9a63f886d216f19c524c70
