### ISSUE TITLE
Game freezes when loading world

### ISSUE THREAD

**Issue by GamerGaven** [team-abnormals/blueprint#139]
I updated to the latest build for blueprint in a custom modpack, there seems to be an incompatibility with both mods: [https://www.curseforge.com/minecraft/mc-mods/the-bumblezone-forge](url)
[https://www.curseforge.com/minecraft/mc-mods/dimensional-dungeons](url)
Tested a couple times in various combinations and this is the crash report it gives me every time:
[crash-2022-02-09_23.42.38-server.txt](https://github.com/team-abnormals/blueprint/files/8039110/crash-2022-02-09_23.42.38-server.txt)

**Comment by SmellyModder** [comment]
A fix for this will get released tomorrow.
