### ISSUE TITLE
Server tick loop crash

### ISSUE THREAD

**Issue by ManaStar** [team-abnormals/blueprint#141]
Not sure what to say on this one, other than that it seems similar to an issue that was supposed to have been fixed in the latest version.

Crash Report: https://pastebin.com/NrUfE6mR

This was on version 5.1.1

**Comment by SmellyModder** [comment]
Discussed over discord 😛

**Comment by SmellyModder** [comment]
I'm going to assume this issue is no longer occurring for you. As I stated over Discord, this is something you must fix.
If this is eventually confirmed to be directly caused by Blueprint, I will reopen this issue.
