### ISSUE TITLE
Blueprint wont load.

### ISSUE THREAD

**Issue by GoldHeartTheOne** [team-abnormals/blueprint#142]
hi Blueprint wont load for me.
MC: 1.18.1
Forge: 39.0.75
Blueprint: 5.1.1

log: https://drive.google.com/file/d/1n3rAg1FiVaDXKzptgIc6y7VkQaZAyEcm/view?usp=sharing
crash report: https://drive.google.com/file/d/1SRH4rFv0Rj_OakBsxrmTK7SJSo4xaS_F/view?usp=sharing

**Comment by SmellyModder** [comment]
I think this is a conflict between Quark and NoRecipeAdvancements, but since Blueprint loads the `ServerAdvancementManager` class, it looks like it's a Blueprint issue.
Try only running Quark and NoRecipeAdvancements and see if the game still doesn't load.

**Comment by GoldHeartTheOne** [comment]
disabling NoRecipeAdvancements allowed Blueprint to load.

**Comment by SmellyModder** [comment]
This is a conflict between Quark and NoRecipeAdvancements, and looks to be resolved in this commit: https://github.com/VazkiiMods/Quark/commit/8caf073d101f25dbbe3132de9cee488409bf5714
