### ISSUE TITLE
[1.18.2] Server crash upon exploring new chunks

### ISSUE THREAD

**Issue by BugmanBugman** [team-abnormals/blueprint#150]
Was exploring newly generated chunks until my server crashed, logs seem to say its something with blueprint.
https://gist.github.com/BugmanBugman/f2cc51922df497938783dba3c1d4612d

**Comment by SmellyModder** [comment]
This is an issue with Terrablender and got fixed in Terrablender's latest version. (https://github.com/Glitchfiend/TerraBlender/commit/a18bf5e65f14c559eb0f000fc0ad17d3b2543d99)
