### ISSUE TITLE
[1.18.2] Startup crash with Supplementaries/Snowy Spirit on  40.0.36+ of forge

### ISSUE THREAD

**Issue by BugmanBugman** [team-abnormals/blueprint#152]
Title. The crash seems to be triggered with those 2 mods alone, and only on forge  40.0.36.
https://gist.github.com/BugmanBugman/2a5a0015b5040382dab0117b9ebdaaa9

**Comment by SmellyModder** [comment]
A recent forge version made a change that breaks one of our mixins.
For now, use forge versions below `40.0.36`.

**Comment by SmellyModder** [comment]
This is fixed in the [latest version](https://www.curseforge.com/minecraft/mc-mods/blueprint/files/3735366) of Blueprint.
