### ISSUE TITLE
(1.18.2) Crash on latest forge version

### ISSUE THREAD

**Issue by Inonedn** [team-abnormals/blueprint#158]
https://pastebin.com/CsyRVQrc

**Comment by SmellyModder** [comment]
Are you running Blueprint in a development environment?
`Reference map 'undergarden.refmap.json' for undergarden.mixins.json could not be read. If this is a development environment you can ignore this message` is mentioned in the crash report.
I also haven't seen anyone else have a crash like this, so I have a feeling something's not quite right.

**Comment by Inonedn** [comment]
I believe Its a mixin issue from blueprint inject attempt

https://pastebin.com/Tbcm1p2e

[09May2022 14:59:35.680] [main/WARN] [mixin/]: @Inject(@At("HEAD")) Shift.BY=1 on blueprint.mixins.json:EntityMixin::handler$zcm000$baseTick exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.

**Comment by Inonedn** [comment]
I found out what's causing it, its Pehkui
