### ISSUE TITLE
All banner patterns registered by blueprint are available in the loom table even without their respective banner pattern items

### ISSUE THREAD

**Issue by thelegitdolt** [team-abnormals/blueprint#163]

**Comment by thelegitdolt** [comment]
<img width="254" alt="Screen_Shot_2022-07-06_at_6 12 20_PM" src="https://user-images.githubusercontent.com/50085439/177726200-3b4a3836-cc73-4416-b522-50d881b0de53.png">

(note the chimpanzee, honeycomb, and windswept's snow charge and snow golem patterns in the end)

**Comment by SmellyModder** [comment]
As I stated in the last issue you opened, Blueprint's `BannerManager` uses the `BannerPattern#create()` method provided by Forge, so this is **not** a Blueprint issue.
In 1.19, a tag is used to determine if a banner pattern needs an item in the loom.
In 1.18.2, the `hasPatternItem` boolean is used from `BannerPattern`.

**Comment by thelegitdolt** [comment]
should i report this to forge then

**Comment by SmellyModder** [comment]
> In 1.19, a tag is used to determine if a banner pattern needs an item in the loom.
> In 1.18.2, the hasPatternItem boolean is used from BannerPattern.

No

**Comment by thelegitdolt** [comment]
i dont understand. Do you mean that Is it the fault of the mods that registering the patterns? but half of the mods are abnormals.

**Comment by SmellyModder** [comment]
Yes, it's the fault of the mods registering the patterns.
