### ISSUE TITLE
(1.18.2) Crash with Immersive Engineering

### ISSUE THREAD

**Issue by KintsugiKitten** [team-abnormals/blueprint#164]
I'm playing with a few mods installed, but I was able to identify the causation of the crash- which gave me the following error code- as Immersive Engineering.
[main/WARN]: @Inject(@At("HEAD")) Shift.BY=1 on blueprint.mixins.json:EntityMixin::handler$zbb000$baseTick exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
This was the last line in the latest.log, and thus the most likely to be the cause of the crash. It was a complete incompatibility, crashed on startup. I was hoping there was a way to fix this without removing either mod.

**Comment by SmellyModder** [comment]
Immersive Engineering is somehow loading the mixin config and overwriting the Forge default mixin config values.
I suppose I could try rewriting our mixins to prevent this issue, but for now, adjusting your mixin config should fix this issue.

**Comment by Giandrys** [comment]
> Immersive Engineering is somehow loading the mixin config and overwriting the Forge default mixin config values. I suppose I could try rewriting our mixins to prevent this issue, but for now, adjusting your mixin config should fix this issue.

i got this problem too, 
How can I adjust my mixin settings?
