### ISSUE TITLE
crash before starting the server

### ISSUE THREAD

**Issue by mraxg** [team-abnormals/blueprint#170]
Hi, I'm trying to create a server with friends and I've added the blueprint mod but it gives me a very strange error and I can't solve it. Can someone help me?
I attach an image of the error immediately after the error the server stops starting.
I think changing this parameter that marks me would solve it but I can't find the file it indicates and I can't find any similar file
Thanks in advance.
![image](https://user-images.githubusercontent.com/111460420/186183814-2cb1e2cc-5e8d-4871-a880-edb708c09705.png)
![image](https://user-images.githubusercontent.com/111460420/186183986-7ae81ab8-9cd5-411f-b926-b27f96364476.png)

**Comment by SmellyModder** [comment]
Same as #164, but possibly not in the same way. Update your mixin configs if possible to allow `maxShiftBy` to be greater than 0 until we fix this.
