### ISSUE TITLE
Finding the mixin.config file

### ISSUE THREAD

**Issue by doubleaxes** [team-abnormals/blueprint#174]
Hi Im using neapolitan mod with blueprint mod and Im trying to change the maxShiftBy value to greater than 0 but I don't know where to find a mixin config file and I dont know which mixin file to edit If there is multiple ones. Thanks in advance.

**Comment by SmellyModder** [comment]
You should ask this question on the SpongePowered Discord Server or other Minecraft Modding Discord servers.
