### ISSUE TITLE
1.18 Incompatibility with terrablender

### ISSUE THREAD

**Issue by linkhidalgogato** [team-abnormals/blueprint#175]
Having blueprint installed prevents BYG (or any other mod that uses terrablender that i tested) from spawning any of its biomes, I was testing it on the latest 1.18 version of blueprint terrablender byg and forge.

**Comment by Atlantispy** [comment]
To add to this, it's specific to terrablender 126.

Think it's the same as #166 but for a lower version, I assume the fix wasn't backported

**Comment by SmellyModder** [comment]
> To add to this, it's specific to terrablender 126.
> 
> Think it's the same as #166 but for a lower version, I assume the fix wasn't backported

Correct, a backport of the fix will be coming soon.
