### ISSUE TITLE
Licensing requirements for this (and therefore all dependent mods) forbids modpacks on curseforge

### ISSUE THREAD

**Issue by AngleWyrm10** [team-abnormals/blueprint#176]
"[The status of the file AngleWyrm's Collection-22.9.3.zip (AngleWyrm's Collection) has been changed to Rejected](https://www.curseforge.com/minecraft/modpacks/anglewyrms-collection/files/3965284)

Notes:
The following files are not allowed to be redistributed due to licensing restrictions:
overrides/mods/blueprint-1.18.2-5.4.4.jar

Modpacks containing these files will not be approved.
If you have any questions please contact our support team https://support.curseforge.com/"

**Comment by bageldotjpg** [comment]
Our mods can be used on modpacks on CurseForge, you just have it set up wrong. Install the mods through the CurseForge launcher again and then export the modpack - you have the mod in as an override.
