### ISSUE TITLE
Increase the value of maxShiftBy

### ISSUE THREAD

**Issue by Giandrys** [team-abnormals/blueprint#177]
Hi, I have a server with mods in aternos.org in which I receive this warning regarding blueprint. but i can't understand.

`@Inject(@At("HEAD")) Shift.BY=1 on blueprint.mixins.json:EntityMixin::handler$zfc000$baseTick exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning`

**Comment by SmellyModder** [comment]
Similar to https://github.com/team-abnormals/blueprint/issues/164, but possibly not caused the same way.
Follow the advice on that issue.
