### ISSUE TITLE
(1.18.2) Blueprint and Terrablender prevent trees/foliage from generating in a new world

### ISSUE THREAD

**Issue by Aero48** [team-abnormals/blueprint#178]
Forge: 40.1.76
Blueprint: 5.4.6
Terrablender: 1.2.0.126

Here's what a freshly generated world looks like: 
![2022-09-04_23 44 37](https://user-images.githubusercontent.com/56200404/188357603-3091ec36-911c-484d-9518-b5d34e7820c0.png)

**Comment by agentwolf88** [comment]
Same

**Comment by KyrDerz** [comment]
Same

**Comment by bageldotjpg** [comment]
https://www.curseforge.com/minecraft/mc-mods/blueprint/files/3970154
