### ISSUE TITLE
Game crashes after launch.

### ISSUE THREAD

**Issue by bontavi** [team-abnormals/blueprint#180]
Minecraft - 1.19.2
Forge - 43.1.25
Blueprint - 5.5.0

I suspect blueprint is a culprit of crash. Since, there is only two mods installed in the pack. After disabling Savage mod, Minecraft still crashes after launch.

logs - https://pastebin.com/ank9T6fp

**Comment by SmellyModder** [comment]
Send the full log. If your game is crashing with only Blueprint installed, that is bizarre because that's happening for nobody else, myself included. I suspect there are unrevealed details, and providing the full log would help me find them.

**Comment by bontavi** [comment]
logs with both Savage and Blueprint only mods - https://pastebin.com/4XRgRtCd
Only with a blueprint mod - https://pastebin.com/MK5ndPHG

**Comment by SmellyModder** [comment]
Ah, that would explain the crash.
