### ISSUE TITLE
Blueprint on Forge profile prevents game from launching

### ISSUE THREAD

**Issue by Stellar-Seeker** [team-abnormals/blueprint#182]
For some reason, Blueprint causes Minecraft to hang in the loading phase forever (not even launching the actual game) after using the official launcher. I've replicated the bug on a fresh profile with just Blueprint, and I genuinely have no idea what the problem here is. I'm not a programmer, and there's no crash files that I've seen.

(Modloader is Forge and the version is 1.19.2)

**Comment by SmellyModder** [comment]
I'm unsure what's causing that, and I haven't heard of anyone having that issue.
Try to send a log if possible and keep trying to isolate conditions.
Unfortunately, there's not much I can do with the information so far.

**Comment by Stellar-Seeker** [comment]
I've been experimenting with this issue a bit more, and a few things I have observed:
1. Simply disabling Blueprint does not solve the issue. It has to be completely removed for Minecraft to successfully boot up.
2. While attempting to run Minecraft with Blueprint disabled, I noticed that OpenJDK (the game) started for a brief moment in Task Manager (under background processes) before disappearing. This happens every time I start a new game.
3. The launcher is still running the entire time I attempt to boot the game, according to the task manager. When I attempt to launch a new game from Forge, I'm told that Minecraft is still considered open even though it functionally isn't.
4. My antivirus (McAfee) seems to be very active whenever Minecraft is running, even though the program's been whitelisted.

**Comment by Stellar-Seeker** [comment]
I have successfully solved the issue and I think it might be due to Forge's modloading messing up.

I manually downloaded a copy of blueprint from the page instead of using the modloader and it works flawlessly now.

Of note is that Blueprint didn't show up on Forge when I searched for it.

**Comment by SmellyModder** [comment]
Strange, probably not a Blueprint issue.
I will reopen this issue if new details arrive.
