### ISSUE TITLE
[1.19.2] tag issue

### ISSUE THREAD

**Issue by YOYOK9** [team-abnormals/blueprint#183]
Would it be possible to add the 1.19.2 to the Blueprint 1.19 - 6.0.7 version? I have tested it and it does work, however in the cf app if you install a mod that needs blueprint in 1.19.2 it will just grab the latest release as there is technically no version for 1.19.2. That release being the 1.18.2 version (currently)

Tested with: 
CF forge profile 1.19.2
Using the app install a mod with blueprint as the dependency (I used Savage & Ravage), Look at the bp version it installed, try to start pack. It will crash.

**Comment by SmellyModder** [comment]
A 1.19.2 version of Blueprint doesn't technically exist yet.
