### ISSUE TITLE
Biome Generation crashes 

### ISSUE THREAD

**Issue by Zelioth** [team-abnormals/blueprint#184]
Recently started having Biome Generation issues and it's blaming a few mods but BluePrint is present in each blame. The Crash report directly points towards blueprint as well and I'm not sure why. will include reports. 

MC : 1.19.2
Forge : 43.1.43
Mod V : 6.1.0

[crash-2022-10-16_15.23.03-server.txt](https://github.com/team-abnormals/blueprint/files/9794751/crash-2022-10-16_15.23.03-server.txt)
[crash-2022-10-16_14.01.44-server.txt](https://github.com/team-abnormals/blueprint/files/9794752/crash-2022-10-16_14.01.44-server.txt)

[crash-2022-10-16_13.48.41-server.txt](https://github.com/team-abnormals/blueprint/files/9794753/crash-2022-10-16_13.48.41-server.txt)

**Comment by SmellyModder** [comment]
Not a Blueprint issue.
`Feature order cycle found` is a vanilla error given when two or more biomes have features in common that are in a different order.
Use the [Cyanide ](https://www.curseforge.com/minecraft/mc-mods/cyanide-forge) mod to get better info.
