### ISSUE TITLE
Missing or unsupported mandatory dependencies:

### ISSUE THREAD

**Issue by MeeMik0ik0** [team-abnormals/blueprint#191]
Setting up server on aternos, blueprint refuses to work despite giving it the version asked for. Is there any fix for it? Going back to 1.19.2 might fix...

> Mod ID: 'minecraft', Requested by: 'blueprint', Expected range: '[1.19.2,1.19.3)', Actual version: '1.19.3'

![image](https://user-images.githubusercontent.com/117740390/226249563-8c86d77b-7c5b-4b68-b6eb-6f17681dfa24.png)

**Comment by SmellyModder** [comment]
Blueprint isn't on 1.19.3 yet.
