### ISSUE TITLE
fail to connect server

### ISSUE THREAD

**Issue by GitJhopa** [team-abnormals/blueprint#201]
![image](https://github.com/team-abnormals/blueprint/assets/86250668/a2212298-d455-4f4b-a1e7-ac2e92c3c2f5)

**Comment by GitJhopa** [comment]
Forge 1.19.2

**Comment by SmellyModder** [comment]
This is not a Blueprint issue. The `ClientInfo.getClientPlayer()` method is a utility method that mods using Blueprint can use.
