### ISSUE TITLE
The Blueprint mod is suspected to crash my game and I have no idea why

### ISSUE THREAD

**Issue by TAKOMAN1** [team-abnormals/blueprint#202]
I am playing in a large mod pack, everything was fine until for some reason my game started crashing every time I enter my single-player world. I enter the world, (I'm in a Taiga Forest biome next to a Snowy Mountain if that matters) and for 20s it's fine until it suddenly crashes for some reason.
In the crash report it says: "Suspected Mods: Blueprint (blueprint), Minecraft (minecraft)".
I attached the crash log, any idea why it keeps crashing?

[crash-2023-07-29_17.01.21-server.txt](https://github.com/team-abnormals/blueprint/files/12207336/crash-2023-07-29_17.01.21-server.txt)

**Comment by SmellyModder** [comment]
This is not a Blueprint issue, "Feature order cycle" is a vanilla error. See issue #197 for further details.
