### ISSUE TITLE
Abnormals logs unable to be turned into Casing w/ Create (1.19.2, although also present in 1.18 and maybe 1.16)

### ISSUE THREAD

**Issue by GodzillaFan13** [team-abnormals/blueprint#207]
Exactly what it says. all Abnormals logs (IDK about Caverns and Chasms or Endergetic since i'm not a patreon currently) are unable to be turned into casing, be it andesite, copper or brass.

**Comment by GodzillaFan13** [comment]
IDK how to change the flair oof

**Comment by SmellyModder** [comment]
Don't report general issues about Abnormal mods to Blueprint.
It looks like Create determines which blocks can be made into casing using this [tag](https://github.com/Creators-of-Create/Create/blob/mc1.19/dev/src/generated/resources/data/create/tags/items/modded_stripped_wood.json).
