### ISSUE TITLE
it keeps laging in the loading terrain screen

### ISSUE THREAD

**Issue by DAIJEAN** [team-abnormals/blueprint#213]
i was playing in my world and i teleported to some place that was kinda far but then it just lagged soo i had to close the game and when i tried to enter the game again everytime i try to enter my word is keeps laging in the "loading terrain" screen and when i try to make a new word it also lag in world generation screen
i checked the crash reports file and it said its because of blueprint mod something about "chunks loading"
how can i solve this ? 
i dont want to lose my world

**Comment by SmellyModder** [comment]
I can't help much without the crash report, so please send it. Blueprint is probably not the cause, but it shows up in the crash report because it modifies biome generation.

**Comment by DAIJEAN** [comment]
> I can't help much without the crash report, so please send it. Blueprint is probably not the cause, but it shows up in the crash report because it modifies biome generation.

Thx for your reply ^^
i did manage to find a solution and its exactly like u said, it is not because of blueprint 
i did add a mod called regions unexplored and i think this mode doesnt work well with blueprint so when i deleted it, it worked again!
