### ISSUE TITLE
Mod Blueprint not loading, help?

### ISSUE THREAD

**Issue by KaranMaia** [team-abnormals/blueprint#215]
Hi, added some mods and having trouble with the Blueprint loading, perhaps someone can help me to know what is happening or what mods are conflicting?

https://pastebin.com/WnK87kJh

https://pastebin.com/MNr9ytZW

**Comment by SmellyModder** [comment]
Looks like a mixin is trying to use a class that doesn't exist.
This shouldn't be possible. Can you see if this crash doesn't happen with only blueprint?

**Comment by brnbrd** [comment]
I am also getting a crash in a different scenario:
TelepathicGrunt/RepurposedStructures#324

**Comment by SmellyModder** [comment]
@brnbrd 
Your crash is unrelated to this issue.
However, I am talking to the Repurposed Structures developer about that issue.

**Comment by KaranMaia** [comment]
> Looks like a mixin is trying to use a class that doesn't exist. This shouldn't be possible. Can you see if this crash doesn't happen with only blueprint?

Yeah, it was a mixer by the ModernFix mod, just deleted the mod from the modpack, thanks guys

**Comment by KaranMaia** [comment]
> Looks like a mixin is trying to use a class that doesn't exist. This shouldn't be possible. Can you see if this crash doesn't happen with only blueprint?

Yeah,it was happening only with the blueprint mod but i found out it was a mixer by the ModernFix mod, just deleted this mod from my mod list, thanks guys
