### ISSUE TITLE
Crash at launch with latest blueprint 7.0.1

### ISSUE THREAD

**Issue by vivagabe** [team-abnormals/blueprint#216]
I get a crash at launch with the latest blueprint. 
[crash-2024-03-01_23.55.36-client.txt](https://github.com/team-abnormals/blueprint/files/14468472/crash-2024-03-01_23.55.36-client.txt)

**Comment by xd4rkzghost01** [comment]
I have the same issue but with the OuterEnd mod (which need Blueprint)
[crash-2024-03-02_11.03.14-fml.txt](https://github.com/team-abnormals/blueprint/files/14469995/crash-2024-03-02_11.03.14-fml.txt)

**Comment by RoomAlex68** [comment]
I also had the same issue as well

**Comment by SmellyModder** [comment]
Both crashes reported here are not Blueprint's fault.

@vivagabe Your crash is caused by Nature's Spirit, which doesn't even support Forge.

@xd4rkzghost01 It looks like Outer End is using classes that we removed in the newest Blueprint version. Report the issue to them.

**Comment by vivagabe** [comment]
@SmellyModder Understood! im using sinytra connector to get it to run that mod. its a nice substitute for atmospheric and environmentals on 1.20.1. I will report the issue to them and hopefully they can find a solution.
