### ISSUE TITLE
Minecraft Crash Report 1.20.1

### ISSUE THREAD

**Issue by Krimatoria** [team-abnormals/blueprint#217]
Connector-1.0.0-beta.37+1.20.1.jar
Gigeresque-connector-1.20.1-0.5.62.jar
Blueprint-1.20.1-7.0.1.jar
SmartBrainLib-forge-1.20.1-1.13.jar

> at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformSingleDescriptor(MixinTargetContext.java:1001) ~[Connector-1.0.0-beta.37+1.20.1.jar%23429%23433!/:0.12.8+mixin.0.8.5] {}

https://gist.github.com/Krimatoria/116dfddef04fb87522a7147ee3c96af0 - Log

**Comment by SmellyModder** [comment]
Looks like a duplicate of #215.
