### ISSUE TITLE
Crash on game startup (forge 1.20.1)

### ISSUE THREAD

**Issue by BurgerBob886** [team-abnormals/blueprint#219]
Game crashes on startup, Not Enough Crashes identifies Blueprint as the culprit. Crash log:
[crash-2024-03-02_19.16.35-fml.txt](https://github.com/team-abnormals/blueprint/files/14472066/crash-2024-03-02_19.16.35-fml.txt)
![image](https://github.com/team-abnormals/blueprint/assets/96219044/0ba8b006-2d69-43a2-be66-944b5eed683e)

Additionally, when paired with certain other mods, such as Sniffer+, it causes them to break and be misidentified as the culprit for the crash (as seen in the next crash log).
[crash-2024-03-02_23.04.58-client.txt](https://github.com/team-abnormals/blueprint/files/14472075/crash-2024-03-02_23.04.58-client.txt)

MC 1.20.1
Forge 47.2.20
Blueprint 1.20.1-7.0.1

**Comment by BurgerBob886** [comment]
Neither issue exists with Blueprint 1.20.1-7.0.0.

**Comment by SmellyModder** [comment]
Looks like an issue with ModernFix. Make sure you are using its newest version.
See https://github.com/embeddedt/ModernFix/commit/e7632b7f0b632fd310683a97c95a65f5db317ea4

ModernFix was unnecessarily patching a blueprint bug that no longer exists, even after I told them it was no longer needed.
