### ISSUE TITLE
[CRASH, NeoForge 1.20.1] Incompatible with old ModernFix versions

### ISSUE THREAD

**Issue by IstasNix** [team-abnormals/blueprint#223]
I'm not totally sure if there's anything you can do about this on your end, but Blueprint and ModernFix do not seem to be compatible. Trying to launch with both results in a crash very early on in the load, which I discovered when I was trying to add a few of the Discord betas to a small modpack for testing. The error Minecraft itself returns just says "_Blueprint (blueprint) has failed to load correctly: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered_," but I have included full crash report and log files below.

I know the beta announcements say they should work on Forge and NeoForge 47.1.3, but the furthest-back download for NeoForge I could find was 47.1.5 (the main website only presents the latest version, and that's as far back as the archive goes) so I initially launched and tested on that. I then tried a few versions I already had installed from testing other packs, and most recently I tried the newest NeoForge version for 1.20.1. On every launch, the result was the same: everything else worked so long as I removed ModernFix, nothing worked if both Blueprint and ModernFix were installed.

I did search the Discord for ModernFix and found no mention of this: the only relevant messages were from people recommending ModernFix to others, most likely for previous versions of Blueprint since no errors were reported.

The crash report and log pastes linked below come from a launch specifically to generate these files, using a modpack with _nothing_ but Blueprint and ModernFix. The error itself does not seem to change when omitting other mods, though.

Crash Report:
https://pastebin.com/Y4NDVuFJ
Log:
https://pastebin.com/uy6TZMqJ

**Comment by SmellyModder** [comment]
This is entirely ModernFix's fault. Use ModernFix's newest version.
I told the ModernFix developer to remove the mixin a long time ago, but I guess they never got the message.
