### ISSUE TITLE
Server crashing 

### ISSUE THREAD

**Issue by andrewtaylor2077** [team-abnormals/blueprint#224]
Server crash on boot 

crash report 
[crash-2024-03-11_19.08.12-server.txt](https://github.com/team-abnormals/blueprint/files/14563894/crash-2024-03-11_19.08.12-server.txt)

**Comment by SmellyModder** [comment]
Their fault: https://github.com/FinnSetchell/MoogsEndStructures/issues/6

Explanation here: https://github.com/team-abnormals/blueprint/issues/218#issuecomment-1975269702
