### ISSUE TITLE
Loading into world leaves me with a black screen

### ISSUE THREAD

**Issue by Hugor728** [team-abnormals/blueprint#228]
I am playing on a modpack called steampunk mc on curseforge, I added more create focused mods, terralith and tetonic, and deco block mods. Yesterday I was able to generate the world and play completely fine. Today I tried to load into the world, got the joining world message and then a flash of the crosshair and then black screen, no sounds to indicate I am inside the world, just a black screen. The crash report says it blueprint but I'm not really sure it might be? Since I was able to play no problems yesterday. Here is my crash report.
Crash report: https://paste.ubuntu.com/p/yJb5ks2xH8/

**Comment by bageldotjpg** [comment]
Yeah not Blueprint's fault, looks to be a worldgen mod - potentially `pangeaultima`, `terralith`, or `byg`, or even an unlisted one.
The [Cyanide](https://www.curseforge.com/minecraft/mc-mods/cyanide) mod may help you track down this issues

**Comment by Hugor728** [comment]
> Yeah not Blueprint's fault, looks to be a worldgen mod - potentially `pangeaultima`, `terralith`, or `byg`, or even an unlisted one. The [Cyanide](https://www.curseforge.com/minecraft/mc-mods/cyanide) mod may help you track down this issues

Thank you! it was pangeaultima :)
