### ISSUE TITLE
Issue with CE's Minerals & More (MCreator Mod)

### ISSUE THREAD

**Issue by PercyJames** [team-abnormals/blueprint#229]
The only reason I disclose that it's MCreator is in case it's unfixable if that's the case.

[crash-2024-04-01_20.29.32-server.txt](https://github.com/team-abnormals/blueprint/files/14830013/crash-2024-04-01_20.29.32-server.txt)
[crash-2024-04-01_20.29.32-server.txt](https://github.com/team-abnormals/blueprint/files/14830014/crash-2024-04-01_20.29.32-server.txt)

**Comment by bageldotjpg** [comment]
This is unrelated to blueprint actually, its falsely blaming it. 
Looks to be a worldgen mod - potentially `cemm`, or `excessive_building`, or even an unlisted one.
The [Cyanide](https://www.curseforge.com/minecraft/mc-mods/cyanide) mod may help you track down this issues

**Comment by PercyJames** [comment]
Wack. I'll try that mod.
