### ISSUE TITLE
Dependent mods asking for version that doesn't exist, crash on startup.

### ISSUE THREAD

**Issue by AnotherVagabond** [team-abnormals/blueprint#235]
Getting a crash on startup with Autumnity and Incubation because they seem to be asking for a version of Blueprint that doesn't exist.

"[11:27:30] [main/ERROR]: Missing or unsupported mandatory dependencies:
	Mod ID: 'blueprint', Requested by: 'autumnity', Expected range: '[7.1.0,)', Actual version: '7.0.3'
	Mod ID: 'blueprint', Requested by: 'incubation', Expected range: '[7.1.0,)', Actual version: '7.0.3'"

Checking the CF page there doesn't seem to be a Blueprint 7.1.0, I feel like it might have been meant to be asking for 7.0.1? Putting this in here just in case there is a 7.1.0 and I just can't figure out where to get it.

**Comment by bageldotjpg** [comment]
Version does exist, download from modrinth
https://modrinth.com/mod/blueprint

Curseforge flagged it for manual review for some reason

**Comment by AnotherVagabond** [comment]
Oh, that'd explain it. Thanks!
