### ISSUE TITLE
NECESIDAD DE ACTUALIZAR BLUEPRINT

### ISSUE THREAD

**Issue by d-rick** [team-abnormals/blueprint#236]
![error blueprint](https://github.com/team-abnormals/blueprint/assets/83624925/f880befe-ae1d-4846-b7d4-79cabe58b316)

No me es posible actualizar ningún mod Abnormal por que me pide una versión de blueprint que al parecer aun no esta disponible, **1.20.1**

**Comment by SmellyModder** [comment]
Curseforge hasn't approved Blueprint 7.1.0 yet, but you can download it from [Modrinth](https://modrinth.com/mod/blueprint/version/7.1.0).
