### ISSUE TITLE
neapolitan and incubation requiere blueprint 7.1.0 or above

### ISSUE THREAD

**Issue by krjencik** [team-abnormals/blueprint#237]
Minecraft 1.20.1 Forge 47.2.30

incubation: 4.0.2
neapolitan: 5.0.0

currently the **(highest)** version of blueprint is 7.0.3

**Comment by bageldotjpg** [comment]
curseforge hasnt approved it for some reason
https://modrinth.com/mod/blueprint/version/7.1.0
