### ISSUE TITLE
blueprint not available for the newest mod updates

### ISSUE THREAD

**Issue by Omega58** [team-abnormals/blueprint#238]
Not really an issue, but i downloaded the newly updated 1.20.1 versions of buzzier bees, upgrade aquatic and autumnity, as well as blueprint.
however, when i load the game, it says that i need blueprint 7.1.0, but it is nowhere to be found on curseforge ! the latest version of blueprint on curseforge is 7.0.3, which means that without this 7.1.0 version, the mods cannot run.

regardless, i hope development of your mods continues to progress in a good way.

yours truly,

**Comment by Omega58** [comment]
i forgot to say i also have woodworks downloaded. sorry !

**Comment by SassyCultist** [comment]
You can find it on modrinth for now it seems!

**Comment by SassyCultist** [comment]
> i forgot to say i also have woodworks downloaded. sorry !

You can find it on modrinth for now!
https://modrinth.com/mod/blueprint/version/7.1.0
