### ISSUE TITLE
Crash with Advanced Compass and Quark possibly

### ISSUE THREAD

**Issue by Apollonu** [team-abnormals/blueprint#246]
[latest.log](https://github.com/user-attachments/files/16075770/latest.log)

[Render thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: class com.teamabnormals.blueprint.common.remolder.RemoldedResourceManager cannot be cast to class net.minecraft.server.packs.resources.MultiPackResourceManager (com.teamabnormals.blueprint.common.remolder.RemoldedResourceManager is in module blueprint@7.1.0 of loader 'TRANSFORMER' @18d610e1; net.minecraft.server.packs.resources.MultiPackResourceManager is in module minecraft@1.20.1 of loader 'TRANSFORMER' @18d610e1)

From Line 8456

**Comment by SmellyModder** [comment]
Advanced Compass appears to be a closed-source mod and is the cause of the crash.
Advanced Compass is unsafely casting the game's resource managers. Report this issue to them, and I'll reopen this issue if it's something only fixable on our side.
