### ISSUE TITLE
Crash while loading world in minecraft 1.20.1

### ISSUE THREAD

**Issue by Billetiado10** [team-abnormals/blueprint#248]
Error generating a new world in minecraft forge 1.20.1 with blueprint installed
The crash report tells me that blueprint is the possible responsible for this.

CRASH REPORT
https://mclo.gs/3xCXPve
Latest Log
https://mclo.gs/7Po3Qrc
DebugLog
https://mclo.gs/QwCp1hE

Blueprint Version
blueprint-1.20.1-7.1.0
Minecraft Forge
1.20.1 47.3.5
Windows 10
Intel Core i79700
GTX 1050 ti 4VRAM

**Comment by BackToEnd** [comment]
I'm having the same issue with any version of Blueprint released for 1.20.1. Downgrading didn't work. For me it's a different biome, though, Frozen Peaks.
Try temporarily removing Blueprint from the pack and see if the issue persists. For me, removing Blueprint doesn't fix the problem. Sometimes crash reports lie and the mod mentioned isn't actually related.
I noticed that our modlists are pretty similar, I'm currently looking into the problem with mine and I'll let you know what caused the problem for me, but if you want to do some investigating try this:
remove half your mods and put them into a separate folder elsewhere, fix dependency issues, see if it works. If it works, add half the removed mods, fix dependency issues, repeat. If it doesn't, switch halves, fix dependency issues, see if it works, repeat.

**Comment by Billetiado10** [comment]
What I'm doing is comparing my personal mod pack with one of the most popular Curseforge mods. I'm checking all the mods they have and adding the same ones since in theory there shouldn't be any errors with those mods.
Maybe the ones that aren't included are the possible problem.

**Comment by BackToEnd** [comment]
That actually fixed the problem for me for the time being, though Cyclic ran fine for me while I was trying to find the issue and had a few mods removed. If another issue of this sort comes up for me I'll see if there are any kinds of incompatibilities, but now at least I can play! Thanks!

**Comment by SmellyModder** [comment]
It's not a Blueprint issue, as you guys have figured out.
Seeing a mod in the stack trace doesn't always mean it's the cause of the crash.
