### ISSUE TITLE
Removing Blueprint makes my server crash on startup.

### ISSUE THREAD

**Issue by padraigpearse** [team-abnormals/blueprint#249]
I started my server with blueprint but quickly realised i have no need for it as i don't have any of the mods that rely on it and as with many other people I'm also having the extremely annoying incompatibility with connected texture mods.  I deleted the mod from both the server and client files and now the server won't run without it.  I readded the mod and it boots up fine but i don't need/want the mod anymore

**Comment by SmellyModder** [comment]
Without logs, I cannot thoroughly diagnose the issue. However, you could try resetting your server's worldgen NBT data to vanilla default.

**Comment by padraigpearse** [comment]
Hi sorry for the late response.  [Here is a link to the crash log when Blueprint is deleted.](https://pastebin.com/JLXZ0Dmj)

**Comment by SmellyModder** [comment]
Looks like an incompatibility with BCLib + Sinytra Connector.

It appears your worldgen settings got corrupted. You're going to have to reset your worldgen settings to vanilla. Many worldgen Discord servers can help you with that if you have trouble.

Sorry for the inconvenience, but critical errors are expected to occur alongside Fabric mods as we don't design Blueprint with those mods in mind.

If I see this issue reoccurring more, I will make a fix. For now, I'm closing this issue.
