### ISSUE TITLE
Problem with server hosting

### ISSUE THREAD

**Issue by silorus** [team-abnormals/blueprint#251]
I tried to use BetterMC modpack for hosting. And this modpack contains nod "blueprint" which doesn't work
![Screenshot_1](https://github.com/user-attachments/assets/0a4eed76-c86a-4efd-b4b4-8628b3a3b468)

**Comment by SmellyModder** [comment]
This is not a Blueprint issue, as something is wrong with your installation.
`RecipeManager` is a vanilla class that should exist in 1.20.1: https://github.com/neoforged/NeoForge/blob/1.20.1/patches/minecraft/net/minecraft/world/item/crafting/RecipeManager.java.patch
