### ISSUE TITLE
[1.20.1] "Loot table validation problem" messages in server logs.

### ISSUE THREAD

**Issue by Norepinephrinee** [team-abnormals/blueprint#252]
Hello,

Server log is filled with messages like **[main/WARN] [minecraft/LootDataManager]: Found loot table element validation problem in {loot_tables:minecraft:chests/musketeer_fort_loot}.pools[2].entries[3].functions[1]: Parameters [<parameter minecraft:tool>] are not provided in this context**, which is possibly a conflict between Blueprint and some of the mods installed because the messages appear after another one mentioning Blueprint and some loot modification manager **main/INFO] [co.te.bl.co.Blueprint/]: Loot Modification Manager has loaded 14 modifier groups**.

Forge 47.3.7, MC 1.20.1

Not sure if it is safe to ignore or is it a Blueprint issue at all or no.
Full log –> [latest (18).log](https://github.com/user-attachments/files/16719173/latest.18.log)

**Modlist:**
- [Let's Do] Bakery – Farm&Charm Compat (2.0.2).jar
- [Let's Do] Brewery – Farm&Charm Compat (2.0.3).jar
- [Let's Do] Candelight – Farm&Charm Compat (2.0.2).jar
- [Let's Do] Farm & Charm (1.0.3).jar
- [Let's Do] HerbalBrews (1.0.8).jar
- [Let's Do] Meadow (1.3.19).jar
- [Let's Do] WilderNature (1.0.3).jar
- [Library] [Let's Do] API (1.2.15).jar
- [Library] Architectury API (9.2.14).jar
- [Library] Blueprint (7.1.0).jar
- [Library] Cloth Config API (11.1.118).jar
- [Library] CoroUtil (1.3.7).jar
- [Library] Curios API (5.9.1).jar
- [Library] GeckoLib (4.4.7).jar
- [Library] YUNG's API (4.0.5).jar
- [Team Abnormals] Clayworks (3.0.1).jar
- [Team Abnormals] Incubation (4.0.2).jar
- [Team Abnormals] Neapolitan (5.0.0).jar
- [Team Abnormals] Upgrade Aquatic (6.0.1).jar
- Ribbits (3.0.0).jar
- Wandering Bags (2.0.7).jar
- Warriors of Past Epoch (1.4).jar
- What Are They Up To (WATUT) (1.1.3).jar
- What Are You Voting For (1.2.5).jar
- Wildberries (1.3.0).jar
- YUNG's Better Desert Temples (3.0.3).jar
- YUNG's Better End Island (2.0.6).jar
- YUNG's Better Jungle Temples (2.0.5).jar
- YUNG's Better Mineshafts (4.0.4).jar
- YUNG's Better Nether Dungeons (4.0.4).jar
- YUNG's Better Nether Fortresses (2.0.6).jar
- YUNG's Better Ocean Monuments (3.0.4).jar
- YUNG's Better Strongholds (4.0.3).jar

**Comment by SmellyModder** [comment]
Doesn't look like a Blueprint issue. The errors in the logs do not suggest Blueprint is a cause.
I'm closing this, but I will reopen it if Blueprint causes the issue.
