### ISSUE TITLE
Cannot find class 'SelectionSpace'

### ISSUE THREAD

**Issue by Munil1** [team-abnormals/blueprint#254]
When i try to run blueprint 7.0.3 or 7.1.0 on forge 1.20.1-47.2.0, it gives me a MixinTransformerError:
"Exception message: org.spongepowered.asm.mixin.throwables.ClassMetadataNotFoundException: com.teamabnormals.blueprint.core.util.modification.selection.SelectionSpace"
[crash-2024-09-28_19.07.22-fml.txt](https://github.com/user-attachments/files/17174569/crash-2024-09-28_19.07.22-fml.txt)

**Comment by SmellyModder** [comment]
This is an incompatibility with ModernFix. Update ModernFix.
