### ISSUE TITLE
[1.19.2] Feature order cycle crash with Atmospheric

### ISSUE THREAD

**Issue by Catomax262** [team-abnormals/blueprint#262]
https://bytebin.lucko.me/0p7hJHx10u - crash log

**Comment by Catomax262** [comment]
P.D: It seems Atmospheric has gotten allergic to lesser biome mods since 1.18

**Comment by SmellyModder** [comment]
It's not a Blueprint issue.
`Feature order cycle found` is an error thrown by vanilla.
Looks like the `naturaldecormod` mod is at fault. You can use the Cyanide mod to get a more detailed crash report.
