### ISSUE TITLE
Mod can't load with mohist

### ISSUE THREAD

**Issue by FurieLunaire** [team-abnormals/blueprint#263]
[crash-2024-11-10_19.03.40-fml.txt](https://github.com/user-attachments/files/17692527/crash-2024-11-10_19.03.40-fml.txt)
Hello, i'm trying to make a server BetterMC with plugins.
I installed mohist but the server can't load

**Comment by SmellyModder** [comment]
```Exception message: java.lang.ClassNotFoundException: net.minecraft.world.item.crafting.RecipeManager``` shouldn't happen in a normal environment. This not a Blueprint issue, but an issue with your installation.
