### ISSUE TITLE
Permission to port to Fabric

### ISSUE THREAD

**Issue by MikelR1** [team-abnormals/blueprint#264]
(this is for all of Team Abnormals mods, not just Blueprint)

Hello, I am reaching out to ask for permission to port Team Abnormal’s actively developed mods to the Fabric modloader. This would come as great benefit, as many people who play modded Minecraft choose to play on the Fabric modloader for one reason or another. Through the use of the Create team’s Porting Lib, I will attempt to keep up to date with any changes, reworks, or updates your mods will have as quick as possible, as porting lib allows fabric ports of forge mods to be much more up-to-date and accurate to the original mod. Anywhere this port is available, I will make it very clear that this port is not officially supported by the Team Abnormals team and to only report any issues found to me. Once you make the decision, please let me know. If you decide against this, it would be unfortunate, but I will respect your decision.

**Comment by SmellyModder** [comment]
We are not currently interested in porting to Fabric, and if such a port existed, we would only want it to be officially supported.
Anyone is always welcome to try porting Blueprint to Fabric, but there is no guarantee it will ever go public.
