### ISSUE TITLE
[1.16 - Compatibility Issue] Crash with Chlorine

### ISSUE THREAD

**Issue by Corvus20** [team-abnormals/blueprint#82]
A report is already open on Chlorine's issue tracker, but I figured I should let you know, too. The game crashes on startup when Chlorine is present, citing mixin apply errors involving abnormals core. 

Logs:
[latest.log](https://github.com/team-abnormals/abnormals-core/files/5990782/latest.log)

**Comment by SmellyModder** [comment]
Does this issue occur only with Abnormals Core and Chlorine installed?

**Comment by Sunrypelican** [comment]
I have verified that it does occur when only Abnormals Core and Chlorine are installed

**Comment by scarha** [comment]
Can confirm this. I am weighing between having abnormals mods or chlorine atm for better client side performance.

**Comment by SmellyModder** [comment]
From my understanding, this is an issue Chlorine must fix on their side.
Chlorine overwrites a method we inject into.

**Comment by WhiteCloud-design** [comment]
I tried to compile this version with "gradlew build" and but "Task:  addRefMapToDeobfJar FAILED".  I attached the --stacktrace output.
[stacktrace.txt](https://github.com/team-abnormals/abnormals-core/files/6382099/stacktrace.txt)

**Comment by SmellyModder** [comment]
Closing since 1.16.5 is no longer supported, and Chlorine isn't updating anymore.
